const userActionTypes = {
	REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
	REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
	REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',

	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS',
	LOGIN_REQUEST_FAIL: 'LOGIN_REQUEST_FAIL',

	LOGOUT_REQUEST: 'LOGOUT_REQUEST',
	LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS',
	LOGOUT_REQUEST_FAIL: 'LOGOUT_REQUEST_FAIL',
};

export default userActionTypes;
