const authorActionTypes = {
	INITIAL_AUTHORS_LOADED: 'INITIAL_AUTHORS_LOADED',

	CREATE_AUTHOR_REQUEST: 'CREATE_AUTHOR_REQUEST',
	CREATE_AUTHOR_SUCCESS: 'CREATE_AUTHOR_SUCCESS',
	CREATE_AUTHOR_FAIL: 'CREATE_AUTHOR_FAIL',

	LOAD_AUTHORS_REQUEST: 'LOAD_AUTHORS_REQUEST',
	LOAD_AUTHORS_SUCCESS: 'LOAD_AUTHORS_SUCCESS',
	LOAD_AUTHORS_FAIL: 'LOAD_AUTHORS_FAIL',
};

export default authorActionTypes;
