const courseActionTypes = {
	COURSES_LOADED: 'COURSES_LOADED',
	COURSE_ADDED: 'COURSE_ADDED',
	COURSE_UPDATED: 'COURSE_UPDATED',
	COURSE_DELETED: 'COURSE_DELETED',
};

export default courseActionTypes;
