const courseActionTypes = {
	INITIAL_COURSES_LOADED: 'INITIAL_COURSES_LOADED',

	CREATE_COURSE_REQUEST: 'CREATE_COURSE_REQUEST',
	CREATE_COURSE_SUCCESS: 'CREATE_COURSE_SUCCESS',
	CREATE_COURSE_FAIL: 'CREATE_COURSE_FAIL',

	DELETE_COURSE_REQUEST: 'DELETE_COURSE_REQUEST',
	DELETE_COURSE_SUCCESS: 'DELETE_COURSE_SUCCESS',
	DELETE_COURSE_FAIL: 'DELETE_COURSE_FAIL',

	LOAD_COURSES_REQUEST: 'LOAD_COURSES_REQUEST',
	LOAD_COURSES_SUCCESS: 'LOAD_COURSES_SUCCESS',
	LOAD_COURSES_FAIL: 'LOAD_COURSES_FAIL',
};

export default courseActionTypes;
